### ISSUE TITLE
Typo in setup question

### ISSUE THREAD

**Issue by kevinashworth** [HaNdTriX/generator-chrome-extension-kickstart#17]
The 4th question asked when I ran the generator from the command line was, "Would you like to a override chrome page?" I think a verb is missing between "to" and "a" — the word "use", perhaps? Also, "a" should probably be "an".

**Comment by HaNdTriX** [comment]
Thanks for reporting. 👍 

[`Would you like to override a chrome page?`](https://developer.chrome.com/extensions/override) 

I will fix this in the next release.
