### ISSUE TITLE
Not waiting for the `clean` task to finish

### ISSUE THREAD

**Issue by AleksueiR** [HaNdTriX/generator-chrome-extension-kickstart#6]
[del](https://www.npmjs.com/package/del) 1.2.1 doesn't return a promise and the build doesn't wait fro the `clean` task to finish. Bumping del's version to 2.0.2 fixes things.

Thanks for the awesome generator!

**Comment by HaNdTriX** [comment]
Tanks a lot for reporting!

This issue has been solved in v2.0.0.
