### ISSUE TITLE
Firefox can't install extension

### ISSUE THREAD

**Issue by oori** [HaNdTriX/generator-chrome-extension-kickstart#9]
Firefox can't install a freshly generated extension out of the box.  Tested both with unpacked & packed, ff & ff-dev-edition.  Add-on installations always spits:
```
There was an error during installation: getURL may not be called before an `id` or `uuid` has been set
```

try "out of the box": 
```
yo chrome-extension-kickstart
gulp build --vendor=firefox
gulp pack --vendor=firefox
```

**Comment by HaNdTriX** [comment]
Adding the following property in your `manifest.json` should help:

    ...
    "__firefox__applications": {
      "gecko": {
        "id": "addon@example.com",
        "strict_min_version": "45.0"
      }
    },
    ...

> `applications` is mandatory for Firefox, and specifies the add-on's ID. It may also be used to specify the minimum and maximum versions of Firefox that this add-on supports.

[More Info](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications)

**Comment by oori** [comment]
**Thanks a lot !**

This works when using "browser_action",   but for whatever (*unrelated?*) reason, I can't make "page_action" work in FF.  The addon loads and functions correctly (_options page, etc.._),   but the extension icon is not seen in FF's address bar  (*in chrome it works*).

I guess this problem isn't related to the original issue,  so I close it..
